apiVersion: v1
kind: Pod                                            
metadata:
  name: my-app   
  labels:
    app: my-app                              
spec:                                                
  containers:
    - image: 864185776221.dkr.ecr.us-west-2.amazonaws.com/junesworld
      name: -latest                            
      ports:
        - containerPort: 8080   
