apiVersion: v1
kind: Service
metadata:
  name: my-app
  labels:
    name: my-app
spec:
  selector:
    app: my-app
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      nodePort: 30080
      protocol: TCP
      
