apiVersion: v1
kind: Service
metadata:
  name: nginxdeploy
  labels:
    name: nginxdeploy
spec:
  selector:
    app: nginxdeploy
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      protocol: TCP
