version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.4.0

jobs:
  deploy-cfn:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup
      - run:
          name: Deploy Cloudformation Template with new Docker image
          command: |
            aws cloudformation create-stack \
            --stack-name circleci
            
   

                

        
workflows:
  build_all:
    jobs:
      - deploy-cfn:
         context:
            - AWS
