version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.4.0

jobs:
  deploy-cfn:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup

      - run: sudo apt-get update
      - run: sudo apt-get install -y python3-pip python-dev
      - run: sudo pip install --upgrade awscli
      - run: aws --version

      - run: 
          name: install kubctl
          command: |
            curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.20.4/2021-04-12/bin/linux/amd64/kubectl
            chmod +x ./kubectl
            mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$PATH:$HOME/bin
            kubectl version --short --client
      - run:
          name: install eksctl
          command: |
             curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
             sudo mv /tmp/eksctl /usr/local/bin
             kubectl version --short --client
             
      
            
      - run:
          name: login
          command: |
              aws ecr get-login-password --region $AWS_DEFAULT_REGION  | docker login --username AWS --password-stdin 864185776221.dkr.ecr.us-west-2.amazonaws.com \
      
      - setup_remote_docker
      
      - run:
          name: Push image to repo  
          command: |
              docker build -t nginxd .
              docker tag latest public.ecr.aws/v0t2j0h8/udacitycapstone
              docker push public.ecr.aws/v0t2j0h8/udacitycapstone

      - run: 
          name: create clusters 
          command: |
              aws eks --region us-west-2 update-kubeconfig --name CapstoneEKS-Iz8RCwIdj7T9
              kubectl apply -f deployment.yml
              kubectl get deployments
              kubectl apply -f service.yaml
              kubectl get services
              kubectl get nodes -o wide


            
       
workflows:
  deployment:
    jobs:
      - deploy-cfn:

          context:
            - AWS
