version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.4.0

jobs:
  build_setup:
    docker:
      # Use the same Docker base as the project
      - image: python:3.7.3-stretch
    
    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: push Docker image
          command: |
              docker build -t hello-world .

  deploy-cfn:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup
      - run:
          name: login
          command: |
            aws ecr get-login-password --region  | docker login --username AWS --password-stdin 864185776221.dkr.ecr.us-west-2.amazonaws.com \
      - run:
          name: create repo
          command: |  
            aws ecr create-repository \
            --repository-name junesworld \
            --image-scanning-configuration scanOnPush=true \
            --region us-west-2

      

      - run:
          name: Push image to repo  
          command: |
              docker tag hello-world:latest aws_account_id.dkr.ecr.us-west-2.amazonaws.com/hello-world:latest
              docker push aws_account_id.dkr.ecr.us-west-2.amazonaws.com/hello-world:latest
          
        
workflows:
  build_all:
    jobs:
      - build_setup
      - deploy-cfn:
          requires:
            - build_setup
          context:
            - AWS
