version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.4.0

jobs:
  deploy-cfn:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup

      - run: sudo apt-get update
      - run: sudo apt-get install -y python3-pip python-dev
      - run: sudo pip install --upgrade awscli
      - run: aws --version

      - run: 
          name: install kubctl
          command: |
            curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.20.4/2021-04-12/bin/linux/amd64/kubectl
            chmod +x ./kubectl
            mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$PATH:$HOME/bin
            kubectl version --short --client
      - run:
          name: install eksctl
          command: |
             curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
             sudo mv /tmp/eksctl /usr/local/bin
             kubectl version --short --client
            
       
workflows:
  deployment:
    jobs:
      - deploy-cfn:

          context:
            - AWS
