orbs:
  aws-ecr: circleci/aws-ecr@7.0.0
version: 2.1
workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:

          context: AWS
          create-repo: true
          dockerfile: Dockerfile
          no-output-timeout: 20m
          path: file://Dockerfile
          repo: junesworld
          skip-when-tags-exist: false
          tag: 'latest,myECRRepoTag'
