
version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.4.0

jobs:
  deploy-cfn:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup
      - run:
          name: Install aws-iam-authenticator
          command: |
            curl -o aws-iam-authenticator curl -o aws-iam-authenticator https://amazon-eks.s3-us-west-2.amazonaws.com/1.13.7/2019-06-11/bin/linux/amd64/aws-iam-authenticator
            chmod +x ./aws-iam-authenticator
            sudo mv ./aws-iam-authenticator /usr/local/bin/aws-iam-authenticator
      
      - run:
          name: Install kubectl
          command: |
            curl -o kubectl https://amazon-eks.s3-us-west-2.amazonaws.com/1.13.7/2019-06-11/bin/linux/amd64/kubectl
            chmod +x ./kubectl
            mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$PATH:$HOME/bin
            echo 'export PATH=$PATH:$HOME/bin' >> ~/.bashrc
            kubectl version --short --client
      - run:
          name: create eks using cloudformation template
          command: |
            aws cloudformation create-stack \
            --region us-west-2 \
            --stack-name my-eks-vpc-stack1 \
            --template-url https://s3.us-west-2.amazonaws.com/amazon-eks/cloudformation/2020-10-29/amazon-eks-vpc-private-subnets.yaml
      - run:
          name: create required IAM role
          command: | 
            aws iam create-role \
            --role-name myAmazonEKSClusterRole \
            --assume-role-policy-document file://"cluster-role-trust-policy.json"
      - run:
          name: attach IAM role
          command: | 
            aws iam attach-role-policy \
            --policy-arn arn:aws:iam::aws:policy/AmazonEKSClusterPolicy \
            --role-name myAmazonEKSClusterRole
      - run:
          name: set-up EKS cluster
          command: |
            aws eks create-cluster \
            --region us-east-2 \
            --name cicluster \
            --kubernetes-version <1.20> \
            --role-arn arn:aws:iam::864185776221:role/myAmazonEKSClusterRole  \
            --resources-vpc-config subnetIds=subnet-06838be412ba9e2f6,subnet-0aeec8eb9408e2093,subnet-00432d2e0d672a207,subnet-0d8b645c21ef4e022,securityGroupIds=sg-09942825d6b0216e3


        
workflows:
  build_all:
    jobs:
      - deploy-cfn:
         context:
            - AWS
