version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.4.0

jobs:
  deploy-cfn:
    parameters:
      stack-name:
        description: Name of the CloudFormation stack
        type: string
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup
      - run:
          name: Deploy Cloudformation Template with new Docker image
          command: |
            aws cloudformation deploy \
            --template cfn/my-template.yml \
            --stack CI_STACK_TEST \
                

workflows:
  deploy:
    - deploy-cfn:
      context:
        - aws
      stack-name: My-Application
