version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.4.0

jobs:
  deploy-cfn:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup
      - run:
          name: login
          command: |
            aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 864185776221.dkr.ecr.us-west-2.amazonaws.com \
      - run:
          name: create repo
          command: |  
            aws ecr create-repository \
            --repository-name Junes-world \
            --image-scanning-configuration scanOnPush=true \
            --region us-east-2
           
          
        
workflows:
  build_all:
    jobs:
      - deploy-cfn:
         context:
            - AWS
