version: 2.1
jobs:
  setup:
    docker:
      - image: circleci/node:10.15.3
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Update npm
          command: "sudo npm install -g npm@latest"
          
test:
  docker:
    - image: circleci/node:10.15.3
  working_directory: ~/app
  steps:
    - restore_cache:
        key: v1-repo-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
    - restore_cache:
        key: dependency-cache-{{ .Branch }}-{{ checksum "package.json" }}
    - run:
        name: Test code
        command: npm test
    - persist_to_workspace:
        root: ~/app
        paths:
          - .


build_image_and_deploy_staging:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/app

    steps:
      - attach_workspace:
          at: ~/app

      - run:
          name: Install awscli and gettext-base
          command: |
            sudo pip3 install awscli
      - run:
          name: Install aws-iam-authenticator
          command: |
            curl -o aws-iam-authenticator curl -o aws-iam-authenticator https://amazon-eks.s3-us-west-2.amazonaws.com/1.13.7/2019-06-11/bin/linux/amd64/aws-iam-authenticator
            chmod +x ./aws-iam-authenticator
            sudo mv ./aws-iam-authenticator /usr/local/bin/aws-iam-authenticator
      - run:
          name: Install kubectl
          command: |
            curl -o kubectl https://amazon-eks.s3-us-west-2.amazonaws.com/1.13.7/2019-06-11/bin/linux/amd64/kubectl
            chmod +x ./kubectl
            sudo mv ./kubectl /usr/local/bin/kubectl
      - run:
          name: install eksctl 
          command: |
            curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
            sudo mv /tmp/eksctl /usr/local/bin


        -run:
            name: create key pair + cluster
            command: |
              aws ec2 create-key-pair --region us-west-2 --key-name myKeyPair
              eksctl create cluster \
              --name my-cluster \
              --region us-west-2 \
              --with-oidc \
              --ssh-access \
              --ssh-public-key myKeyPair \
              --managed
workflows:
    jobs:
      - setup
      - test:
          requires:
            - setup
      - build_image_and_deploy_staging:
          requires:
            - test

