version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.4.0

jobs:
  deploy-cfn:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup

      - run: sudo apt-get update
      - run: sudo apt-get install -y python3-pip python-dev
      - run: sudo pip3 install --upgrade awscli
      - run: aws --version



      - run:
          name: login
          command: |
            aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com \
      - run:
          name: create repo
          command: |  
            aws ecr create-repository \
            --repository-name junesworld \
            --image-scanning-configuration scanOnPush=true \
            --region $AWS_DEFAULT_REGION

      

      - run:
          name: Push image to repo  
          command: |
              docker build -t hello-world .
              docker tag hello-world:latest aws_account_id.dkr.ecr.us-west-2.amazonaws.com/hello-world:latest
              docker push aws_account_id.dkr.ecr.us-west-2.amazonaws.com/hello-world:latest
          
        
workflows:
  build_all:
    jobs:

      - deploy-cfn:

          context:
            - AWS
